#!/bin/bash
#===================================================================
basedir=/home/XBBJT69
destdir=$basedir/bhav/output
db=$basedir/data/BhavDB
sqlite=/usr/bin/sqlite3
#-------------------------------------------------------------------
[[ -z "$*" ]] && { tables="Open Close Low High Trade PrevClose YearVolatility DayVolatility LogReturn PrevVolatility DelPer DelQty TrdQty"; } || { tables=$*; }
for table in $tables; do
	printf "Output...$table\n";
	csvfile=$destdir/$table".csv"
	[[ -r $csvfile ]] && { rm $csvfile; } 
	$sqlite $db -csv -header -cmd ".output $csvfile" "select * from company left join $table on company.ISIN=$table.ISIN where company.Series='EQ'"
done
