#!/bin/bash
#===================================================================
basedir=/home/XBBJT69
destdir=$basedir/bhav/output
db=$basedir/data/BhavDB
sqlite=/usr/bin/sqlite3
combfile=$destdir/"all.csv"
#-------------------------------------------------------------------
getopts ":c" opt
shift $((OPTIND -1))
[[ -z "$*" ]] && { tables="Open Close Low High Trade PrevClose YearVolatility DayVolatility LogReturn PrevVolatility DelPer DelQty TrdQty AvgTrd AvgWtVol DifClose DifCloseHigh DifHighLow DifOpenLow"; } || { tables=$*; }
[[ -r $combfile ]] && { rm $combfile; } 
header="-header"
for table in $tables; do
	printf "Output $table ..";
	csvfile=$destdir/$table".csv"
	[[ -r $csvfile ]] && { rm $csvfile; } 
	$sqlite $header -csv -cmd ".output $csvfile" $db "select '$table' as Source,* from company left join $table on company.ISIN=$table.ISIN where company.Series='EQ'"
	[[ $opt == "c" ]] && { cat $csvfile >> $combfile; header=""; } 
	printf ".Done\n";
done